  version: 2
  updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "08:00"
        timezone: "America/Los_Angeles"
      reviewers:
        - "hosseinsh"
        - "csine-nflx"
        - "charhate"
        - "jtschladen"
    - package-ecosystem: "npm"
        directory: "/"
        schedule:
          interval: "weekly"
          day: "monday"
          time: "08:00"
          timezone: "America/Los_Angeles"
        reviewers:
          - "hosseinsh"
          - "csine-nflx"
          - "charhate"
          - "jtschladen"