  version: 2
  updates:
    - directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "08:00"
        timezone: "America/Los_Angeles"
      package-ecosystem: "pip"
      reviewers:
        - "DataDog/edge-ingress"
      ignore:
        - dependency-name: "cert-orchestration-adapter"
      versioning-strategy: auto
      open-pull-requests-limit: 20
