variables:
  CURRENT_CI_IMAGE: registry.ddbuild.io/lemur/ci:0.1.0
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: lemur

stages:
  - test
  - build-stage-image
  - build-prod-image

test:
  image: $CURRENT_CI_IMAGE
  stage: test
  timeout: 30m
  tags: ["arch:amd64"]
  variables:
    POSTGRES_DB: lemur
    POSTGRES_USER: lemur
    POSTGRES_PASSWORD: lemur
    POSTGRES_HOST_AUTH_METHOD: trust
    # Enable colors in pytest output: https://github.com/pytest-dev/pytest/issues/7443
    PY_COLORS: 1
    # Enable colors in chalk output: https://github.com/chalk/chalk#chalklevel
    FORCE_COLOR: 1
  services:
    - registry.ddbuild.io/images/mirror/postgres:12.7
  script:
    # Setup virtualenv
    - python3 -m venv ~/env && \
    - source ~/env/bin/activate && \
    - python3 -m pip install --upgrade pip setuptools coveralls bandit
    # Run tests
    - make test
    - bandit -r . -ll -ii -x lemur/tests/,docs
    - xvfb-run make test-js

build-stage-image:
  image: $CURRENT_CI_IMAGE
  stage: build-stage-image
  when: on_success
  # the 3h timeout is required for images compiling large projects for ARM using qemu
  # we can revert back to 1h when we use native builders for ARM
  timeout: 3h
  tags: ["arch:amd64"]
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true"
  script:
    - cd publish && docker buildx build --label target=staging --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --tag registry.ddbuild.io/lemur:v$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA --push .
  except:
    - tags

# build a prod image when we create a new tag
build-prod-image:
  image: $CURRENT_CI_IMAGE
  stage: build-prod-image
  when: on_success
  # the 3h timeout is required for images compiling large projects for ARM using qemu
  # we can revert back to 1h when we use native builders for ARM
  timeout: 3h
  tags: ["arch:amd64"]
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true"
  script:
    - cd publish && docker buildx build --label target=prod --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --tag registry.ddbuild.io/lemur:$CI_COMMIT_TAG --push .
  only:
    - tags
