--- Dockerfile
+++ Dockerfile
@@ -1,7 +1,7 @@
 FROM python:3.7.9-alpine3.12
 
 ARG VERSION
-ENV VERSION master
+ENV VERSION 6beb04393b5b7c9994384749126e550aae191eec
 
 ARG URLCONTEXT
 
@@ -12,7 +12,7 @@ ENV group lemur
 
 RUN addgroup -S ${group} -g ${gid} && \
     adduser -D -S ${user} -G ${group} -u ${uid} && \
-    apk add --no-cache --update python3 py-pip libldap postgresql-client nginx supervisor curl tzdata openssl bash && \
+    apk add --no-cache --update python3 py-pip libldap postgresql-client nginx supervisor curl tzdata openssl bash build-base libstdc++ libc6-compat && \
     apk --update add --virtual build-dependencies \
                 git \
                 tar \
@@ -35,7 +35,7 @@ RUN addgroup -S ${group} -g ${gid} && \
                 cyrus-sasl-dev \
                 openldap-dev && \
     mkdir -p /opt/lemur /home/lemur/.lemur/ && \
-    curl -sSL https://github.com/Netflix/lemur/archive/$VERSION.tar.gz | tar xz -C /opt/lemur --strip-components=1 && \
+    curl -sSL https://github.com/Datadog/lemur/archive/$VERSION.tar.gz | tar xz -C /opt/lemur --strip-components=1 && \
     pip3 install --upgrade pip && \
     pip3 install --upgrade setuptools && \
     mkdir -p /run/nginx/ /etc/nginx/ssl/ && \
@@ -53,9 +53,12 @@ RUN echo "Running with python:" && python -c 'import platform; print(platform.py
 
 COPY entrypoint /
 COPY src/lemur.conf.py /home/lemur/.lemur/lemur.conf.py
+COPY src/auth.json /tmp/auth.json
+COPY src/staging-auth.json /tmp/staging-auth.json
 COPY supervisor.conf /
 COPY nginx/default.conf /etc/nginx/conf.d/
 COPY nginx/default-ssl.conf /etc/nginx/conf.d/
+RUN chown -R $user:$group /opt/lemur/ /home/lemur/.lemur/
 
 RUN chmod +x /entrypoint
 WORKDIR /
