version: '3'

volumes:
  pg_data: { }

services:
  postgres:
    image: "postgres:13.1-alpine"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env

  lemur:
    # image: "netlix-lemur:latest"
    restart: on-failure
    build:
      context: .
    depends_on:
      - postgres
      - redis
    env_file:
      - lemur-env
      - pgsql-env
    ports:
      - 87:80
      - 447:443
      - 5000:5000
    volumes:
      - /Users/mitch.cail/dd/lemur:/opt/lemur
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://lemur:12345@postgres:5432/lemur
      VIRTUAL_ENV: 'true'
      LEMUR_CONF: "/home/lemur/.lemur/lemur.conf.py"
    stdin_open: true
    tty: true

  redis:
    image: "redis:alpine3.12"
    restart: on-failure
    ports:
      - 6379:6379
