volumes:
  pg_data: { }

services:
  postgres:
    image: "postgres:13.1-alpine"
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env

  lemur:
    image: "lemur:local-dev"
    restart: on-failure
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - lemur-env
      - pgsql-env
    ports:
      - 127.0.0.1:87:80
      - 127.0.0.1:447:443

  redis:
    image: "redis:alpine3.12"
    restart: on-failure
