# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domains/cert_orchestration/libs/pb/cert_orchestration_adapter/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKdomains/cert_orchestration/libs/pb/cert_orchestration_adapter/service.proto\x12\x11\x63\x65rtorchestration\"\xe5\x01\n\x18\x43\x65rtificateUploadRequest\x12 \n\x0b\x63\x65rtificate\x18\x01 \x01(\tR\x0b\x63\x65rtificate\x12\"\n\x0cintermediate\x18\x02 \x01(\tR\x0cintermediate\x12\x1f\n\x0bprivate_key\x18\x03 \x01(\tR\nprivateKey\x12\x1d\n\nvault_path\x18\x04 \x01(\tR\tvaultPath\x12\x43\n\x1e\x64\x61ngerously_skip_sanity_checks\x18\x05 \x01(\x08R\x1b\x64\x61ngerouslySkipSanityChecks\"\x1b\n\x19\x43\x65rtificateUploadResponse\"8\n\x17ListCertificatesRequest\x12\x1d\n\nvault_path\x18\x01 \x01(\tR\tvaultPath\"S\n\x10VaultCertificate\x12 \n\x0b\x63\x65rtificate\x18\x01 \x01(\tR\x0b\x63\x65rtificate\x12\x1d\n\nvault_path\x18\x02 \x01(\tR\tvaultPath\"c\n\x18ListCertificatesResponse\x12G\n\x0c\x63\x65rtificates\x18\x01 \x03(\x0b\x32#.certorchestration.VaultCertificateR\x0c\x63\x65rtificates2\xd3\x01\n\x0b\x43\x65rtificate\x12\x63\n\x06Upload\x12+.certorchestration.CertificateUploadRequest\x1a,.certorchestration.CertificateUploadResponse\x12_\n\x04List\x12*.certorchestration.ListCertificatesRequest\x1a+.certorchestration.ListCertificatesResponseB\\ZZgithub.com/DataDog/dd-source/domains/cert_orchestration/libs/pb/cert_orchestration_adapterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lemur.plugins.lemur_coa.pb.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZZgithub.com/DataDog/dd-source/domains/cert_orchestration/libs/pb/cert_orchestration_adapter'
  _globals['_CERTIFICATEUPLOADREQUEST']._serialized_start=99
  _globals['_CERTIFICATEUPLOADREQUEST']._serialized_end=328
  _globals['_CERTIFICATEUPLOADRESPONSE']._serialized_start=330
  _globals['_CERTIFICATEUPLOADRESPONSE']._serialized_end=357
  _globals['_LISTCERTIFICATESREQUEST']._serialized_start=359
  _globals['_LISTCERTIFICATESREQUEST']._serialized_end=415
  _globals['_VAULTCERTIFICATE']._serialized_start=417
  _globals['_VAULTCERTIFICATE']._serialized_end=500
  _globals['_LISTCERTIFICATESRESPONSE']._serialized_start=502
  _globals['_LISTCERTIFICATESRESPONSE']._serialized_end=601
  _globals['_CERTIFICATE']._serialized_start=604
  _globals['_CERTIFICATE']._serialized_end=815
# @@protoc_insertion_point(module_scope)
